### ISSUE TITLE
Feature request: Add number of unread highlights/private messages to dock icon.

### ISSUE THREAD

**Issue by robertjacobsen** [MacIrssi/MacIrssi#7]
One of the features I miss the most from counterparts such as Linkinus and Adium (its IRC implementation isn’t really all that bad) is the possibility to see how many unread messages or highlights you have in the dock icon. As it’s possible with Growl notifications on highlights (and private messages, if I’m not mistaken?), it could perhaps be implemented by using the same event handler to update a counter.

**Comment by ghost** [comment]
So thinking about the actual look/feel. You want the Mail.app style red star/lozenge with a number counter inside it? MI already pops up the exclamation mark icon if you have new unread private messages, presumably that isn't enough?

**Comment by robertjacobsen** [comment]
Yes, a number count (on blue or red background, dunno what looks the prettiest) would be awesome. The exclamation mark kind of works, but having exact count is, at least to me, very helpful. This could potentially remove the exclamation mark to have a unified icon at all times.

**Comment by ismail** [comment]
This would be pretty.

**Comment by ghost** [comment]
Added in commit 440879029797eafb1bb7e5a332cc128529bf2697. Using the default NSDockTile badge style (I didn't realise this existed, otherwise I'd have done it a long time ago).

It's also only showing you the number of notifications since you last had MacIrssi in the foreground. Having it display unread notifications, until you read them in that specific window, is much more involved.

**Comment by ghost** [comment]
Closing.
